server:
  port: 8088

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
#        - AddResponseHeader=Access-Control-Allow-Credentials, true
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
#            allowedOrigins: "http://5.63.154.191:8098"
            allowedOrigins: "http://localhost:8098"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
            allowedHeaders:
              - Access-Control-Allow-Credentials
              - Access-Control-Allow-Origin
              - Authorization
              - Content-type
              - X-requested-with
              - Cache-Control
              - x-xsrf-token
              - Accept
              - Origin
              - X-file-name
              - content-type
              - authorization
      routes:
        - id: admin-panel
          uri: lb://ADMIN-PANEL
          predicates:
            - Path=/admin-panel/**
          filters:
            - JwtAuthFilter
            - StripPrefix=1
            - PrefixPath=/api/v1/admin-console
        - id: auth-service
          uri: lb://AUTHORIZATION
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1/auth
        - id: users-service
          uri: lb://USERS
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1
#            - JwtAuthFilter
        - id: messages-service
          uri: lb://MESSAGE-SERVICE
          predicates:
            - Path=/dialogs/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1/dialogs
            - JwtAuthFilter
        - id: notifications-service
          uri: lb://NOTIFICATIONS
          predicates:
            - Path=/notifications/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1/notifications
            - JwtAuthFilter
        - id: friends-service
          uri: lb://FRIENDS
          predicates:
            - Path=/friends/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1/friends
            - JwtAuthFilter
        - id: search-service
          uri: lb://SEARCH
          predicates:
            - Path=/search/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1/search
            - JwtAuthFilter
        - id: posts-service
          uri: lb://POSTS
          predicates:
            - Path=/post/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1/post/
            - JwtAuthFilter


jwt:
  secret: aXH6JwuebH3qnxLVWQMXxHHg8euc7pkZ246yUJsMFsLHGGhXzCdanoV3HNiTgZf7
  lifetime: 3600000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://5.63.154.191:8087/eureka
  instance:
    hostname: 5.63.154.191
