server:
  port: 8088

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfiguration:
          '[/**]':
            allowedOrigins: "http://5.63.154.191:8098"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - UPDATE
              - PUT
            allowedHeaders:
              - authorization
              - content-type
              - x-requested-with
              - cache-control
              - x-xsrf-token
              - accept
              - origin
              - x-file-name
      routes:
        - id: admin-panel
          uri: lb://ADMIN-PANEL
          predicates:
            - Path=/admin/**
          filters:
            - JwtAuthFilter
        - id: auth-service
          uri: lb://AUTH-MICRO-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1/auth
        - id: users-service
          uri: lb://USERS_MS
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1/account
            - JwtAuthFilter
        - id: messages-service
          uri: lb://MESSAGE-SERVICE
          predicates:
            - Path=/messages/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1/dialogs
            - JwtAuthFilter
        - id: notifications-service
          uri: lb://NOTIFICATIONS-SERVICE
          predicates:
            - Path=/notifications/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1/notifications
            - JwtAuthFilter
        - id: friends-service
          uri: lb://FRIENDS
          predicates:
            - Path=/friends/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api/v1/friends
            - JwtAuthFilter



jwt:
  secret: aXH6JwuebH3qnxLVWQMXxHHg8euc7pkZ246yUJsMFsLHGGhXzCdanoV3HNiTgZf7
  lifetime: 3600000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://5.63.154.191:8087/eureka
  instance:
    hostname: 5.63.154.19