spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: ${DB_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: none

#liquibase:
#  enabled: true
#  changeLog: db/changelog/db:changelog-master-test.yaml

