spring.datasource.url: jdbc:mysql://localhost:3306/task?useUnicode=true&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: 608370
spring.jpa.hibernate.ddl-auto: create-drop